on: push

jobs:
  setup:
    name: The setup job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a print command
        run: echo "Teeeeeext!!!"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: karlasfb/fmi-cicd-2023
