on: push

jobs:
  setup:
    name: The pipeline initial setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checking out the code

      - name: Print an text
        run: echo "My first text"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: karlasfb/fmi-cicd-2023:${{ GITHUB_RUN_ATTEMPT }}

